### ISSUE TITLE
Exception at entering latitude and longitude

### ISSUE THREAD

**Issue by dml33** [bremor/bureau_of_meteorology#103]
Hi.

When I install this integration, automatically my latitude and longitude data appear in the corresponding fields. When I click on Submit, an unknown error appears. This is the log:

```
This error originated from a custom integration.

Logger: custom_components.bureau_of_meteorology.config_flow
Source: custom_components/bureau_of_meteorology/PyBoM/collector.py:42
Integration: Bureau of Meteorology (documentation, issues)
First occurred: 00:26:10 (1 occurrences)
Last logged: 00:26:10

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/bureau_of_meteorology/config_flow.py", line 49, in async_step_user
    await self.collector.async_update()
  File "/config/custom_components/bureau_of_meteorology/PyBoM/collector.py", line 95, in async_update
    await self.format_daily_forecast_data()
  File "/config/custom_components/bureau_of_meteorology/PyBoM/collector.py", line 42, in format_daily_forecast_data
    days = len(self.daily_forecasts_data["data"])
KeyError: 'data'
```

My location is around Madrid, Spain.

Thanks!

**Comment by DavidFW1960** [comment]
Yeah this is an Australian weather service and doesn't cover Spain.

**Comment by Makin-Things** [comment]
As David commented this is an integration for Australian weather information.
