### ISSUE TITLE
Failed to setup without Internet

### ISSUE THREAD

**Issue by purcell-lab** [bremor/bureau_of_meteorology#113]
When my HA instance starts I often don't have Internet as the router is in the process of loging in. 

The BoM integration treats this as an error and doesn't retry at after a suitable interval, so is never restored.

![image](https://user-images.githubusercontent.com/79175134/165195268-93b38801-8c81-4e62-9285-21bd30446296.png)

If I manually restart the component after the Internet is up everything is fine.

Would it be possible for this integration to retry connection and perhaps make this a warning rather than a hard error?

```
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/bureau_of_meteorology/PyBoM/collector.py:87
Integration: Bureau of Meteorology (documentation, issues)
First occurred: 8:49:43 AM (1 occurrences)
Last logged: 8:49:43 AM

Error setting up entry Noosa Heads for bureau_of_meteorology
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1154, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 880, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/bureau_of_meteorology/__init__.py", line 35, in async_setup_entry
    await collector.async_update()
  File "/config/custom_components/bureau_of_meteorology/PyBoM/collector.py", line 87, in async_update
    async with session.get(URL_BASE + self.geohash) as resp:
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.weather.bom.gov.au:443 ssl:default [Try again]

**Comment by Makin-Things** [comment]
I have tested and confirmed that this is a bug. @glenn20 has offered some possible ways to fix and hopefully can help with a fix.

**Comment by glenn20** [comment]
PR #123 includes a proposed fix:

- Trap error on attempt to connect to BoM services in async_setup_entry() and raise ConfigEntryNotReady so HA will retry the config. HA will keep retrying the config and after network access is available, the config setup completes successfully.
- Until the config setup completes, devices will have "unavailable" status.

**Comment by glenn20** [comment]
@Makin-Things : I went for Option 2 as Option 1 causes some cascading issues about handling unavailable data.

**Comment by Makin-Things** [comment]
I thought that option 2 might have been the better route, but was not sure. I will do a bunch of testing tomorrow for different scenarios.

**Comment by Makin-Things** [comment]
@purcell-lab there is a 1.1.8b pre-release available now that should fix this problem. Are you able to test?

**Comment by purcell-lab** [comment]
Thanks, this is resolved.
