### ISSUE TITLE
Integration v1.1.8 not working

### ISSUE THREAD

**Issue by DancerV** [bremor/bureau_of_meteorology#130]
Not sure exactly what information you need so let's start with this:

Home Assistant Core 2022.6.4
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.1

2022-06-08 16:21:24 INFO (MainThread) [homeassistant.bootstrap] Setting up stage 2: {'ipp', 'mobile_app', 'growatt_server', 'upnp', 'logbook', 'input_select', 'counter', 'persistent_notification', 'input_button', 'sun', 'trace', 'map', 'scene', 'media_source', 'group', 'default_config', 'cast', 'blueprint', 'lifx', 'system_health', 'tag', 'automation', 'my', 'rpi_power', 'uptime', 'mqtt', 'dlna_dmr', 'timer', 'input_datetime', 'application_credentials', 'history', 'input_text', 'tts', 'hacs', 'spotify', 'plex', 'energy', 'zha', 'climate', 'xbox', 'input_boolean', 'brother', 'input_number', 'bureau_of_meteorology', 'device_tracker', 'unifi', 'zone', 'script'}
2022-06-08 16:21:24 INFO (MainThread) [homeassistant.setup] Setting up bureau_of_meteorology
2022-06-08 16:21:24 INFO (MainThread) [homeassistant.setup] Setup of domain bureau_of_meteorology took 0.0 seconds
2022-06-08 16:21:36 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Broadmeadows for bureau_of_meteorology
File "/config/custom_components/bureau_of_meteorology/__init__.py", line 65, in async_setup_entry

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/bureau_of_meteorology/__init__.py", line 65, in async_setup_entry
    name=f"BOM observation {entry.data[CONF_WEATHER_NAME]}",
KeyError: 'weather_name'

**Comment by DancerV** [comment]
(Also v1.1.10)

**Comment by Makin-Things** [comment]
You appear to be the only person reporting this issue. Can I ask if you have any other weather related integrations installed as it looks like it possibly could be a conflict.

**Comment by DancerV** [comment]
None (other than the HA sun default integration). It was working just fine until I updated it to v1.1.8 (I did an HA core update in the same reboot, admittedly).

**Comment by DancerV** [comment]
Deleted the integration, restarted, reinstalled the integration, restarted - and now we seem to be fine. Should have tried that sooner.
