### ISSUE TITLE
weather and wind entities failed

### ISSUE THREAD

**Issue by joe-sydney** [bremor/bureau_of_meteorology#145]
Hi there, I have been using this integration for a while now, but it suddenly broke not long ago. The weather entity and the wind speed entity failed to be created.

I am on HA 2022.6.7 which I upgraded to some days ago and the integration did not have any issues. I am using v1.1.10 of the integration and even downgraded to 1.1.8 to check, but the issues are there. I have not upgraded to 1.1.13 because I am waiting for 2022.7 to stabilise first.

I see the following in the logs:

2022-07-08 15:58:38 ERROR (MainThread) [homeassistant.components.weather] Error adding entities for domain weather with platform bureau_of_meteorology
Traceback (most recent call last):
  File "/srv/hass2/lib/python3.9/site-packages/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/srv/hass2/lib/python3.9/site-packages/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/srv/hass2/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 809, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/home/homeassistant/.homeassistant/custom_components/bureau_of_meteorology/weather.py", line 52, in async_added_to_hass
    self._update_callback()
  File "/home/homeassistant/.homeassistant/custom_components/bureau_of_meteorology/weather.py", line 57, in _update_callback
    self.async_write_ha_state()
  File "/srv/hass2/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
    self._async_write_ha_state()
  File "/srv/hass2/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 573, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/srv/hass2/lib/python3.9/site-packages/homeassistant/components/weather/__init__.py", line 237, in state_attributes
    self.hass.config.units.wind_speed(wind_speed, unit),
  File "/srv/hass2/lib/python3.9/site-packages/homeassistant/util/unit_system.py", line 164, in wind_speed
    raise TypeError(f"{wind_speed!s} is not a numeric value.")
TypeError: unavailable is not a numeric value.
2022-07-08 15:58:38 ERROR (MainThread) [homeassistant.components.weather] Error while setting up bureau_of_meteorology platform for weather
Traceback (most recent call last):
  File "/srv/hass2/lib/python3.9/site-packages/homeassistant/helpers/entity_platform.py", line 257, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/srv/hass2/lib/python3.9/site-packages/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/srv/hass2/lib/python3.9/site-packages/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/srv/hass2/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 809, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/home/homeassistant/.homeassistant/custom_components/bureau_of_meteorology/weather.py", line 52, in async_added_to_hass
    self._update_callback()
  File "/home/homeassistant/.homeassistant/custom_components/bureau_of_meteorology/weather.py", line 57, in _update_callback
    self.async_write_ha_state()
  File "/srv/hass2/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
    self._async_write_ha_state()
  File "/srv/hass2/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 573, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/srv/hass2/lib/python3.9/site-packages/homeassistant/components/weather/__init__.py", line 237, in state_attributes
    self.hass.config.units.wind_speed(wind_speed, unit),
  File "/srv/hass2/lib/python3.9/site-packages/homeassistant/util/unit_system.py", line 164, in wind_speed
    raise TypeError(f"{wind_speed!s} is not a numeric value.")
TypeError: unavailable is not a numeric value.

**Comment by Makin-Things** [comment]
Can you share you lat/lon so I can create the same entities. Just remove a few of the least significant digits so that it doesn't reveal your exact location. I am suspecting that the BoM may have published some bad data.

**Comment by joe-sydney** [comment]
Thanks for the quick response. You can try the following coordinates- they give the same errors.


Thanks!

**Comment by Makin-Things** [comment]
A quick check shows that there may be a problem with that Sydney Olympic Park weather station in that there is no wind data, which then flows on to  the apparent temp.

**Comment by joe-sydney** [comment]
OK, thanks. It may resolve itself after awhile then. Will report back. Has never happened before.

**Comment by Makin-Things** [comment]
I am not able to get the same errors as you, but I no longer have any instance of HA on 2022.6.x, but I see that the wind sensors are ``unavailable``. That is because of a bom issue since their site shows no wind info either.
[https://weather.bom.gov.au/location/r3grt8x-sydney-olympic-park](url)
By the time I can install an old version of HA to test they will probably have fixed it. Let me know if it continues to be a problem though.

**Comment by joe-sydney** [comment]
OK, I changed to another weather station close by and all is good. Will revert back to SOP tomorrow once they have the wind data. Maybe it would be good to not break the weather.xxx entity if some isolated data like wind is missing, but all good, this is not mission critical :)

Thanks for looking into this.

**Comment by Makin-Things** [comment]
There is a chance that some of the more recent updates to the Bom integration has resolved this. tbh. I don't think that is the case, but for me with the latest HA and BoM 1.1.13 I  didn't get the errors you posted.
I agree though that it should not break when the BoM have issues. Keep me informed.

**Comment by joe-sydney** [comment]
Things have returned to normal with the SOP weather station stats. Did you want me to close this as an issue, or keep it open in case others experience this with a view to handle bad/missing data gracefully? It may not be easy to test this with 1.1.13 waiting for similar bad data from BOM.

**Comment by Makin-Things** [comment]
If it is no longer an issue for you I'd prefer to close. Others can still comment if they have a similar issue.
