### ISSUE TITLE
Integration is not updating data.

### ISSUE THREAD

**Issue by thetonto** [bremor/bureau_of_meteorology#168]
Been using the integration since I switched over to home assistant (about 6 months now).  All working fine but recently have noticed that it is not updating and now only updates when I restart home assistant.  Have turned on debugging and will post anything interesting as I find it.

Debug info on startup which may be helpful:

`2023-01-29 08:04:51.430 DEBUG (MainThread) [custom_components.bureau_of_meteorology] Finished fetching bureau_of_meteorology data in 0.000 seconds (success: True)
2023-01-29 08:04:53.461 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform bureau_of_meteorology
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 438, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 709, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 803, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/bureau_of_meteorology/sensor.py", line 162, in async_added_to_hass
    self._update_callback()
  File "/config/custom_components/bureau_of_meteorology/sensor.py", line 166, in _update_callback
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 556, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 600, in _async_write_ha_state
    attr.update(self.extra_state_attributes or {})
  File "/config/custom_components/bureau_of_meteorology/sensor.py", line 215, in extra_state_attributes
    attr["time_observed"] = iso8601.parse_date(self.collector.observations_data["data"][self.sensor_name]["time"]).astimezone(tzinfo).isoformat()
TypeError: 'NoneType' object is not subscriptable
2023-01-29 08:04:53.561 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up bureau_of_meteorology platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 297, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 438, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 709, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 803, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/bureau_of_meteorology/sensor.py", line 162, in async_added_to_hass
    self._update_callback()
  File "/config/custom_components/bureau_of_meteorology/sensor.py", line 166, in _update_callback
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 556, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 600, in _async_write_ha_state
    attr.update(self.extra_state_attributes or {})
  File "/config/custom_components/bureau_of_meteorology/sensor.py", line 215, in extra_state_attributes
    attr["time_observed"] = iso8601.parse_date(self.collector.observations_data["data"][self.sensor_name]["time"]).astimezone(tzinfo).isoformat()
TypeError: 'NoneType' object is not subscriptable`

**Comment by thetonto** [comment]
Couple of days later.  Can see confirm the issue is with the forecast.  Other items are updating regularly.

**Comment by Makin-Things** [comment]
Assuming this was just an issue with the BoM.
