### ISSUE TITLE
Upgrading BoM error

### ISSUE THREAD

**Issue by haggis663** [bremor/bureau_of_meteorology#174]
After upgrading component, I am getting the following error:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 709, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/bureau_of_meteorology/__init__.py", line 16, in <module>
    from .const import (
  File "/config/custom_components/bureau_of_meteorology/const.py", line 139, in <module>
    device_class=SensorDeviceClass.PRECIPITATION,
  File "/usr/local/lib/python3.10/enum.py", line 437, in __getattr__
    raise AttributeError(name) from None
AttributeError: PRECIPITATION

**Comment by Napoleon-BlownApart** [comment]
You probably need to update your HA installation.
I had the same error when I was running an old HAOS image (2022) and after updating it, the problem went away.

However, I now have a different problem, where the component is partially working; I have my satellite image background centered on my location, but NO rain data (though the BOM's radar site clearly shows the rain that's presently falling).  I don't know how to fix this yet and am considering opening a `Issue`.

**Comment by geejayem99** [comment]
If you're referring to the BOM radar card, that's a different project to this one and it is broken at the moment due to changes by BOM. More info at https://github.com/Makin-Things/bom-radar-card/issues/32

**Comment by Makin-Things** [comment]
Stale.
