### ISSUE TITLE
Home assistant 2023.8.3 - fails to load

### ISSUE THREAD

**Issue by DJS91** [bremor/bureau_of_meteorology#186]
Home assistant 2023.8.3 integration fails to load.

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/bureau_of_meteorology/PyBoM/collector.py:87
Integration: Bureau of Meteorology (documentation, issues) 
First occurred: 7:02:37 PM (3 occurrences) 
Last logged: 7:03:27 PM

Error setting up entry Alexandra Hills for bureau_of_meteorology
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bureau_of_meteorology/__init__.py", line 70, in async_setup_entry
    await collector.async_update()
  File "/config/custom_components/bureau_of_meteorology/PyBoM/collector.py", line 87, in async_update
    self.locations_data = await resp.json()
                          ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://api.weather.bom.gov.au/v1/locations/r7hgqy')

**Comment by DJS91** [comment]
Ignore this. Newest build fixed it
