### ISSUE TITLE
Repeated errors: "Error doing job: Task exception was never retrieved (None)"

### ISSUE THREAD

**Issue by VlastiBroucek** [bremor/bureau_of_meteorology#239]
Home Assistant

Core 2024.12.0
Supervisor 2024.11.4
Operating System 14.0
Frontend 20241127.4

```log
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/bureau_of_meteorology/sensor.py:247
integration: Bureau of Meteorology (documentation, issues)
First occurred: 14:27:24 (3 occurrences)
Last logged: 14:37:29

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 267, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 478, in _async_refresh
    self.async_update_listeners()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 177, in async_update_listeners
    update_callback()
    ~~~~~~~~~~~~~~~^^
  File "/config/custom_components/bureau_of_meteorology/sensor.py", line 203, in _update_callback
    self.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1023, in async_write_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1148, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1089, in __async_calculate_state
    if extra_state_attributes := self.extra_state_attributes:
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bureau_of_meteorology/sensor.py", line 247, in extra_state_attributes
    attr["time_observed"] = iso8601.parse_date(self.collector.observations_data["data"][self.sensor_name]["time"]).astimezone(tzinfo).isoformat()
                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

```

**Comment by Prythi** [comment]
Getting the same as well as the following with generally accompanies it....

This error originated from a custom integration.

Logger: custom_components.bureau_of_meteorology
Source: helpers/update_coordinator.py:379
integration: Bureau of Meteorology (documentation, issues)
First occurred: 2:29:55 PM (1 occurrences)
Last logged: 2:29:55 PM

Unexpected error fetching bureau_of_meteorology data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 379, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 280, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bureau_of_meteorology/PyBoM/collector.py", line 93, in async_update
    if self.observations_data["data"]["wind"] is not None:
       ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'data'

**Comment by systemtester** [comment]
@Makin-Things I'll take a look at this over the weekend.  Unsure if you've change 1.3.4 from pre-release but this might be another quick one that can go in it.

**Comment by Makin-Things** [comment]
@systemtester thanks for looking into all these issues, I did do a full 1.3.4 release once the previous problem was fixed.
I generally will create a pre-release and do my own testing and if that goes well I remove the pre-release checkbox.  I don't generally have a lot of time to spend on this stuff atm, but will happilly merge PR's and do releases. I will merge this when I get home tonight and do a 1.3.5 preview.

**Comment by systemtester** [comment]
All good mate.  RL > FOSS.  Have tested locally but will run checks against the Pre-release as well if you ping me.  Edit: @Makin-Things I've got a couple of other fixes lined up outside the PR with you at the moment.  If you hold on creating a pre-release for a week or so I can almost close the entire issue list except for a couple.

**Comment by Makin-Things** [comment]
OK. Will hold off until you ping me asking for the pre-release.

**Comment by systemtester** [comment]
Fixed in 1.3.5 @Makin-Things This can be closed.
