### ISSUE TITLE
Sensor for extended text not updating - extended text field too large?

### ISSUE THREAD

**Issue by Zoogara** [bremor/bureau_of_meteorology#50]
Noticed some errors in the log for sensor XXX_extended_text_4, see below.  This causes the sensor not to update . See example of extended_text_3 and _4 showing different update times.

**extended_text_3:**

response_timestamp: 2020-12-03T04:47:18Z
issue_time: 2020-12-03T04:17:01Z
forecast_region: North East
forecast_type: public-district
attribution: Data provided by the Australian Bureau of Meteorology
friendly_name: Rutherglen Extended Text 3

**extended_text_4:**

response_timestamp: 2020-12-02T12:55:43Z
issue_time: 2020-12-02T10:33:48Z
forecast_region: North East
forecast_type: public-district
attribution: Data provided by the Australian Bureau of Meteorology
friendly_name: Rutherglen Extended Text 4

**Log error:**

Logger: homeassistant
Source: core.py:871
First occurred: 0:06:13 (1879 occurrences)
Last logged: 15:45:17

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 283, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 408, in _async_write_ha_state
    self.hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1185, in async_set
    state = State(
  File "/usr/src/homeassistant/homeassistant/core.py", line 871, in __init__
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity id: sensor.rutherglen_extended_text_4. State max length is 255 characters.

**Comment by Zoogara** [comment]
Sorry also should have made it clearer, this issue isn't with specific extended text sensor, I expect tomorrow the issue will appear on extended_text_3, extended_text 4 will be fine (assuming it also isn't too long).

**Comment by Zoogara** [comment]
No - error still occurring on sensor 4.  This may indicate it's an issue with sensor 4 I suppose - or they could have changed the text.

Logger: homeassistant
Source: core.py:871
First occurred: 3 December 2020, 0:06:13 (3747 occurrences)
Last logged: 14:49:30

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 283, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 408, in _async_write_ha_state
    self.hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1185, in async_set
    state = State(
  File "/usr/src/homeassistant/homeassistant/core.py", line 871, in __init__
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity id: sensor.rutherglen_extended_text_4. State max length is 255 characters.

**Comment by bremor** [comment]
Thanks for raising this! Shouldn’t be too hard to resolve. I will look into this when I get a chance.

**Comment by bremor** [comment]
**Hopefully** fixed in release 0.10.1 - please let me know if you still encounter this issue.
