### ISSUE TITLE
HACS installation custom_components error in log

### ISSUE THREAD

**Issue by prle77** [bremor/bureau_of_meteorology#64]
Hi guys.. 
although everything seem to be working.. looking at the log files I can see this error popping up.. 
`Logger: homeassistant
Source: custom_components/bureau_of_meteorology/sensor.py:180
First occurred: January 4, 2021, 4:04:37 PM (146 occurrences)
Last logged: 11:14:44 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 119, in _handle_refresh_interval
    await self.async_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 193, in async_refresh
    update_callback()
  File "/config/custom_components/bureau_of_meteorology/sensor.py", line 105, in _update_callback
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 296, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 323, in _async_write_ha_state
    attr.update(self.device_state_attributes or {})
  File "/config/custom_components/bureau_of_meteorology/sensor.py", line 180, in device_state_attributes
    attr[ATTR_DATE] = self.collector.daily_forecasts_data["data"][self.day]["date"]
IndexError: list index out of range`

It was working fine before.. .. I'm running 

version: 2020.12.2
installation_type: Home Assistant OS
dev: false
hassio: true
docker: true
virtualenv: false
python_version: 3.8.6
os_name: Linux
os_version: 5.4.79-v7l
arch: armv7l
timezone: Australia/Sydney
host_os: Home Assistant OS 5.9
update_channel: stable
supervisor_version: 2020.12.7
docker_version: 19.03.13

**Comment by bremor** [comment]
Fixed in 0.10.2
https://github.com/bremor/bureau_of_meteorology/releases/tag/0.10.2
