### ISSUE TITLE
Losing integration every time I reboot...

### ISSUE THREAD

**Issue by Rusti-gotrage** [bremor/bureau_of_meteorology#81]
So when I initially set-up the integration in HA, it works fine, but if I restart HA for any reason, the integration breaks.

I'm getting the following error when it breaks:

2021-06-11 17:14:31 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Craigieburn for bureau_of_meteorology
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/bureau_of_meteorology/__init__.py", line 35, in async_setup_entry
    await collector.get_location_name()
  File "/config/custom_components/bureau_of_meteorology/PyBoM/collector.py", line 70, in get_location_name
    response = await session.get(url)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 890, in start
    message, payload = await self._protocol.read()  # type: ignore
  File "/usr/local/lib/python3.8/site-packages/aiohttp/streams.py", line 604, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

If I remove it from the INTEGRATIONS and re-add it - it works perfectly... until the next time the system restarts....

Any ideas?

**Comment by bremor** [comment]
Should be fixed in v1.0.0, see here https://github.com/bremor/bureau_of_meteorology/issues/78#issuecomment-960592316
