### ISSUE TITLE
Error: certificate verify failed: unable to get local issuer certificate

### ISSUE THREAD

**Issue by nixmaster2000** [bremor/bureau_of_meteorology#82]
I had this working for some time but lost it after an update.  I had this error originally and fixed it somehow but I can't for the life of me find what that fix was - I think it was disabling verify_ssl somewhere. I've tried removing and re-adding the integration but the error persists.

My HA instance is running on a QNAP NAS as a qpkg application (ie not through Docker) 2021.6.5 and BOM 0.10.3

`Unexpected exception
Traceback (most recent call last):
  File "/opt/Home-Assistant/lib/python3.8/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/opt/Home-Assistant/lib/python3.8/asyncio/base_events.py", line 1046, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/opt/Home-Assistant/lib/python3.8/asyncio/base_events.py", line 1076, in _create_connection_transport
    await waiter
  File "/opt/Home-Assistant/lib/python3.8/asyncio/sslproto.py", line 529, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/opt/Home-Assistant/lib/python3.8/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/opt/Home-Assistant/lib/python3.8/ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/Home-Assistant/CONFIG_DIR/custom_components/bureau_of_meteorology/config_flow.py", line 46, in async_step_user
    result = await self.collector.get_location_name()
  File "/share/CACHEDEV1_DATA/.qpkg/Home-Assistant/CONFIG_DIR/custom_components/bureau_of_meteorology/PyBoM/collector.py", line 70, in get_location_name
    response = await session.get(url)
  File "/opt/Home-Assistant/lib/python3.8/site-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/opt/Home-Assistant/lib/python3.8/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/opt/Home-Assistant/lib/python3.8/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/opt/Home-Assistant/lib/python3.8/site-packages/aiohttp/connector.py", line 1051, in _create_direct_connection
    raise last_exc
  File "/opt/Home-Assistant/lib/python3.8/site-packages/aiohttp/connector.py", line 1020, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/opt/Home-Assistant/lib/python3.8/site-packages/aiohttp/connector.py", line 971, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host api.weather.bom.gov.au:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')]`

**Comment by nixmaster2000** [comment]
Solved my own problem by downloading one of the older releases marked "ssl=False" and copied the associated lines from the collector.py file into the new one - back up and running now. I realise this probably isn't an ideal scenario but until I know how to solve the problem properly this will have to do.
