### ISSUE TITLE
Integration taking too long to load

### ISSUE THREAD

**Issue by bremor** [bremor/bureau_of_meteorology#90]
I seem to have lost all my observation sensors since updating. Anyone else?

EDIT: a reload of the integration did not help but reinstalling it did.

Edit 2: while it does eventually load, something isn’t right.

![image](https://user-images.githubusercontent.com/34525505/142602837-16a3692b-71be-45a2-8be3-0afed05717d2.png)

**Comment by tomlut** [comment]
I enabled debug logging for the integration but it started flawlessly. Will keep an eye on it.

**Comment by tomlut** [comment]
```
2021-11-19 21:22:09 ERROR (MainThread) [custom_components.bureau_of_meteorology] Timeout fetching BOM observation Blackmans Bay data
2021-11-19 21:22:09 DEBUG (MainThread) [custom_components.bureau_of_meteorology] Finished fetching BOM observation Blackmans Bay data in 301.658 seconds (success: False)
```
...(lots of received data)...
```
2021-11-19 21:32:10 INFO (MainThread) [custom_components.bureau_of_meteorology] Fetching BOM observation Blackmans Bay data recovered
2021-11-19 21:32:10 DEBUG (MainThread) [custom_components.bureau_of_meteorology] Finished fetching BOM observation Blackmans Bay data in 1.596 seconds (success: True)
```

**Comment by Swamp-Ig** [comment]
Doesn't work for me either

**Comment by tomlut** [comment]
I just restarted and the failure of this integration to load is preventing home assistant from starting.

**Comment by tomlut** [comment]
Oh. It finally gave up.

```
Logger: homeassistant.components.weather
Source: custom_components/bureau_of_meteorology/weather.py:161
Integration: Weather (documentation, issues)
First occurred: 00:24:47 (2 occurrences)
Last logged: 00:24:47

Error adding entities for domain weather with platform bureau_of_meteorology
Error while setting up bureau_of_meteorology platform for weather
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 607, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 714, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/bureau_of_meteorology/weather.py", line 50, in async_added_to_hass
    self._update_callback()
  File "/config/custom_components/bureau_of_meteorology/weather.py", line 55, in _update_callback
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 521, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/weather/__init__.py", line 206, in state_attributes
    if self.forecast is not None:
  File "/config/custom_components/bureau_of_meteorology/weather.py", line 161, in forecast
    hours = len(self.collector.hourly_forecasts_data["data"])
TypeError: 'NoneType' object is not subscriptable

```

**Comment by tomlut** [comment]
Another restart and it loaded correctly.

**Comment by rpimeekle** [comment]
I get something similar, except the TypeError is `'NoneType' object is not iterable`.  I have noticed that it seems to fail when the data goes out of range, or is null.  At least, that's what it looked like to me.

```
Logger: custom_components.bureau_of_meteorology
Source: helpers/update_coordinator.py:193
Integration: Bureau of Meteorology (documentation, issues)
First occurred: 29 November 2021, 13:35:03 (55 occurrences)
Last logged: 13:28:28

2021-12-01 01:29:15 ERROR (MainThread) [custom_components.bureau_of_meteorology] Timeout fetching BOM observation West Ulverstone data
2021-12-01 02:14:19 ERROR (MainThread) [custom_components.bureau_of_meteorology] Timeout fetching BOM observation West Ulverstone data
2021-12-01 03:29:27 ERROR (MainThread) [custom_components.bureau_of_meteorology] Timeout fetching BOM observation West Ulverstone data
2021-12-01 04:14:33 ERROR (MainThread) [custom_components.bureau_of_meteorology] Timeout fetching BOM observation West Ulverstone data
2021-12-01 04:59:37 ERROR (MainThread) [custom_components.bureau_of_meteorology] Timeout fetching BOM observation West Ulverstone data
2021-12-01 06:24:46 ERROR (MainThread) [custom_components.bureau_of_meteorology] Timeout fetching BOM observation West Ulverstone data
2021-12-01 06:24:46 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
await self._async_refresh(log_failures=True, scheduled=True)
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
update_callback()
File "/config/custom_components/bureau_of_meteorology/sensor.py", line 64, in _update_callback
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
extra_state_attributes = self.device_state_attributes
File "/config/custom_components/bureau_of_meteorology/sensor.py", line 101, in device_state_attributes
attr.update(self.collector.observations_data["data"]["station"])
TypeError: 'NoneType' object is not iterable
```

**Comment by bremor** [comment]
I think I have solved this one, I am just testing it at the moment, should be ready soon. I was doing some silly things with aiohttp.ClientSession()

**Comment by tomlut** [comment]
Let us know if you want some beta testers.

**Comment by tomlut** [comment]
Looks fixed to me.

**Comment by Watison** [comment]
Thanks for the work @bremor. No sensors showing up for me though? What am I doing wrong?

Installed via HACS, added the following to YAML and restarted...

```
-logger:
 - default: warn
 - logs:
 -   custom_components.bureau_of_meteorology: debug
```

**Comment by ghost** [comment]
I had a similar problem. Resolved by disabling IPv6. Haven't looked into the cause yet.

**Comment by StormyKnight17** [comment]
I'm getting this issue too. Sometimes it loads fast, other times many minutes. I recently disabled IPv6 from my network cards & then it seemed to work ok for a while. Yesterday & today it is back to taking a long time on restart.

**Comment by DavidFW1960** [comment]
> I recently disabled IPv6 from my network cards & then it seemed to work ok for a while.

It's nothing to do with IPv6

**Comment by StormyKnight17** [comment]
Thanks, what is it to do with? 

Cheers
Richard

**Comment by StormyKnight17** [comment]
Had a few days of reloading quickly, thought maybe due to beginning of the month, but back to taking a long time again today 4/MAR/22

**Comment by Makin-Things** [comment]
I believe version 1.1.0 fixed this issue.
If you still have problems please create a new issue with details.

**Comment by StormyKnight17** [comment]
Thanks, it seems to have been working well recently. 

Cheers
Richard
