### ISSUE TITLE
Error adding entities for domain weather with platform bureau_of_meteorology

### ISSUE THREAD

**Issue by rark-ha** [bremor/bureau_of_meteorology#96]
I started getting this error today and the weather domain won't load any items. It appears to be related to 'wind_direction' from the traceback log.

``
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 613, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 747, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/bureau_of_meteorology/weather.py", line 50, in async_added_to_hass
    self._update_callback()
  File "/config/custom_components/bureau_of_meteorology/weather.py", line 55, in _update_callback
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 505, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 540, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/weather/__init__.py", line 230, in state_attributes
    if (wind_bearing := self.wind_bearing) is not None:
  File "/config/custom_components/bureau_of_meteorology/weather.py", line 90, in wind_bearing
    return self.collector.observations_data["data"]["wind_direction"]
KeyError: 'wind_direction'
``

I looked at the BoM website observations and wind direction may be not recording at the moment? [and it is windy!]

![image](https://user-images.githubusercontent.com/62318984/150062070-cf38185d-1350-40a6-82e4-acefa6f33e3a.png)

Though the attribute may be a BoM issue (?) the other items should still load so it doesn't fail the whole integration.

**Comment by DavidFW1960** [comment]
Similar problem today with 'feels like' and humidity. BOM site shows them as dashes as well. The integration needs to handle these missing sensors a bit better. For me they just disappeared. The sensors exist

**Comment by Makin-Things** [comment]
If appears that when wind data is not available the json data simply has the whole wind/gust structures set to null which causes a bit of a problem. Looking into a fix.

**Comment by Makin-Things** [comment]
There is a pre-release, 1.1.1b that should create the sensors correctly but set the values to unavailable.

**Comment by Makin-Things** [comment]
Fixed in 1.1.2
