### ISSUE TITLE
Integration Stopped - Logs suggest it can no longer communicate with BOM API (Have they blocked us?)

### ISSUE THREAD

**Issue by dalewright** [bremor/bureau_of_meteorology#97]
### Log file

Error setting up entry Lal Lal for bureau_of_meteorology
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1154, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 880, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 313, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/bureau_of_meteorology/__init__.py", line 35, in async_setup_entry
    await collector.async_update()
  File "/config/custom_components/bureau_of_meteorology/PyBoM/collector.py", line 84, in async_update
    async with session.get(URL_BASE + self.geohash) as resp:
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.weather.bom.gov.au:443 ssl:default [Try again]

**Comment by bremor** [comment]
Strange indeed... it is still working for me.

Do you mind switching on debugging?
```
logger:
  default: warning
  logs:
    custom_components.bureau_of_meteorology: debug
```

**Comment by dalewright** [comment]
Thank you.

After I turned on logging configuration, I rebooted the host and magically the integration restarted.

Apologies for not rebooting my host before raising the issue.

Thank you for an uniquely Aussie integration mate!

**Comment by bremor** [comment]
No worries! It could've been an issue with your internet connection at the time perhaps.

**Comment by dalewright** [comment]
Thank you. Its great to have local/accurate/free weather data in Home Assistant. Your a good man!

**Comment by DavidFW1960** [comment]
They were doing maintenance yesterday. My temp etc were all missing. The humidity and apparent temp went awol a week ago and are still missing.

**Comment by dalewright** [comment]
Cheers @DavidFW1960 

@bremor The issue is occurring again today. I suspect @DavidFW1960 is right, BOM are diddling with the API end-point :)

**Comment by DavidFW1960** [comment]
you can check here
http://www.bom.gov.au/nsw/observations/nswall.shtml?ref=hdr
that's for NSW and it looks ok right now... (I'm at Gosford)
Yesterday this page said it was down for maintenance
http://www.bom.gov.au/products/IDN60801/IDN60801.94782.shtml
The dewpoint, apparent temp and humidity have been gone for a few weeks but the pressure has been missing for years

**Comment by dalewright** [comment]
I wonder if the VIC storms are causing their servers to be hammered. My integration has been coming on and off all day. The joy of an always on home assistant dashboard
