### ISSUE TITLE
Error parsing JSON data as at 07-Feb-2022 during startup.

### ISSUE THREAD

**Issue by greggo74** [bremor/bureau_of_meteorology#99]
HA v2022.2.4
HACS v1.22.0
BOM Integration v1.1.1

Last couple of days have started getting this error during startup.

Error setting up entry Ashburton for bureau_of_meteorology
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 327, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/bureau_of_meteorology/__init__.py", line 35, in async_setup_entry
    await collector.async_update()
  File "/config/custom_components/bureau_of_meteorology/PyBoM/collector.py", line 85, in async_update
    self.locations_data = await resp.json()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://api.weather.bom.gov.au/v1/locations/r1r0t1')

Has the BOM JSON data changed?  It seems valid.
{"metadata":{"response_timestamp":"2022-02-09T03:32:17Z"},"data":{"geohash":"r1r0t1","timezone":"Australia/Melbourne","latitude":-37.87261962890625,"longitude":145.0689697265625,"marine_area_id":"VIC_MW005","tidal_point":"VIC_TP027","has_wave":false,"id":"Ashburton-r1r0t1","name":"Ashburton","state":"VIC"}}

**Comment by Makin-Things** [comment]
I have just started helping with this project. Are you still having this issue?

**Comment by Makin-Things** [comment]
Closing as no response forthcoming.
